### ISSUE TITLE
Are there breaking changes in 4.0+?

### ISSUE THREAD

**Issue by tswaters** [node-oauth/node-oauth2-server#162]
Just coming from [node-oauth2-server#740 ](https://github.com/oauthjs/node-oauth2-server/issues/740) and I see there was a major version bump from 3 -> 4, but the chnagelog doesn't show any breaking changes.  Was there anything to warrant a major bump?  I'm wanting to switch to this package in a project I have and am unsure if I need to worry about breaking changes.

**Comment by jankapunkt** [comment]
Hi @tswaters thank your for interest in this package. We did the major bump mainly to have a clean break from the original project. Besides that you should be able to upgrade without no major breaks.

However there are minor things that may be "breaking", depending on how you view it. Especially you should check on `changed` and `fixed` in the [changelog](https://github.com/node-oauth/node-oauth2-server/blob/master/CHANGELOG.md).

All of these changes/fixes were considered as required in order to comply with the standard or fix issues.
However, if you find issues after the upgrade that are considered as "major" breaks then please let us know.

**Comment by tswaters** [comment]
Thanks for the quick response, this answers my question.
