### ISSUE TITLE
auth0 mfa-otp

### ISSUE THREAD

**Issue by Uzlopak** [node-oauth/node-oauth2-server#59]
Did somebody ever implemented a mfa-otp grant flow like auth0 did?

**Comment by HappyZombies** [comment]
I did, though it's not an appropriate grant flow -- I can provide an example of what I did, it essentially is a middle layer that sits on top of my authorization_code grant type.

Are there any RFC guide lines for MFA for OAuth that we can maybe implement here? I really don't see anything on the official one.

**Comment by Uzlopak** [comment]
I would be happy if you could provide me the example. 

I think MFA is defined in the Financial Grade API.

**Comment by Uzlopak** [comment]
@HappyZombies 

I dont want to pressure you but can you tell me, when you could provide me your code, please? 

Thx.

**Comment by HappyZombies** [comment]
I'll try to get something by EOD or next week, I'll throw it on the example repo. Probably be an in memory database though to speed things up

**Comment by jankapunkt** [comment]
@Uzlopak great to see you here :-D What do you both about adding this to the examples repo?

**Comment by HappyZombies** [comment]
Yup I am actually making the code in the example repo :)

**Comment by Uzlopak** [comment]
I really hope you can give me that middleware. In the meantime I start to extend oauth2-server with

- AssociateHandler like https://auth0.com/docs/login/mfa/ropg-mfa/enroll-and-challenge-otp-authenticators#enroll-authenticator
- AuthenticatorsHandler like https://auth0.com/docs/login/mfa/ropg-mfa/enroll-and-challenge-email-authenticators#challenge-with-email
- ChallengeHandler https://auth0.com/docs/login/mfa/ropg-mfa/enroll-and-challenge-email-authenticators#challenge-user-with-otp

Is there any interest in adding this feature to this project?

**Comment by jankapunkt** [comment]
@Uzlopak regarding the last comment I think this should be discussed in the examples repo, right @HappyZombies ?

**Comment by HappyZombies** [comment]
We can still talk here since we already got the thread going, once I put the example up 

@jankapunkt This isn't really some middleware, but really just extra functionality that sits on top of the authorization_code flow -- though I am sure it can be used as custom grant extension that this module provides. 

I will try my best to get you an example tonight! But essentially, we have a `/login` route that dispatches a two factor request, if successful we store the users id in a session and the authorization_code grant will take an additional field called twoFactorCode (or whatever you want) along with the scope,  scope, state, response_type, redirect_uri, and client_id.

When we call [.authorize](https://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#authorize-request-response-options-callback), we supply the `authenticateHandler` that validates the two factor code and returns the user that is trying to login (with the assistance of the session that has the user id).

**Comment by HappyZombies** [comment]
@Uzlopak I added the example here https://github.com/node-oauth/node-oauth2-server-examples/tree/feature.mfa-example/mfa-example Keep in mind again that this a custom implementation and doesn't follow anything in particular. Uses everything in memory. 

This example is not quiet done yet, I still gotta mock/implement some small things, but the overall part of it is done :) Please let me know if you have any questions. 

(Also keep in mind I kinda just threw this together, maybe with more time I can make a real working example with MySQL maybe)

**Comment by Uzlopak** [comment]
Thank you ;)
